<?php

if (!defined('BASEPATH')) exit('No direct script access allowed');  

class Relatorio extends PHPExcel {

    public function __construct() {
        parent::__construct();
        $this->load->library('excel');
    }

    public function coordenadores()
    {
		// Create new PHPExcel object
		$objPHPExcel = new PHPExcel();
		 
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("mohamadikhwan.com")
									 ->setLastModifiedBy("mohamadikhwan.com")
									 ->setTitle("Office 2007 XLSX Test Document")
									 ->setSubject("Office 2007 XLSX Test Document")
									 ->setDescription("Test document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									 ->setCategory("Test result file");
		 
		 
		// Add some data
		$objPHPExcel->setActiveSheetIndex(0)
		            ->setCellValue('A1', 'Hello')
		            ->setCellValue('B2', 'world!')
		            ->setCellValue('C1', 'bonjour')
		            ->setCellValue('C2', 'monde')
		            ->setCellValue('A4', 'tutorial from: mohamadikhwan.com');
		 
		// Rename worksheet (worksheet, not filename)
		$objPHPExcel->getActiveSheet()->setTitle('createdUsingPHPExcel');
		 
		 
		// Set active sheet index to the first sheet, so Excel opens this as the first sheet
		$objPHPExcel->setActiveSheetIndex(0);
		 
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();
		 
		//this is the header given from PHPExcel examples. but the output seems somewhat corrupted in some cases.
		//header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
		//so, we use this header instead.
		header('Content-type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="mohamadikhwan_dot_com_phpexcel_tut.xlsx"');
		header('Cache-Control: max-age=0');
		 
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('php://output');
    }
}